Update upload-release.yml

diff --git a/.github/workflows/upload-release.yml b/.github/workflows/upload-release.yml
--- a/.github/workflows/upload-release.yml
+++ b/.github/workflows/upload-release.yml
@@ -27,10 +27,27 @@ jobs:
         ./install.sh
         . ./export.sh
 
+    - name: Debug Info
+      run: |
+        pwd
+        ls -R
+        cat sdkconfig || echo "sdkconfig not found"
+        cat partitions.csv || echo "partitions.csv not found"
+
     - name: Build project
       run: |
         . $HOME/esp/esp-idf/export.sh
-        idf.py build
+        idf.py reconfigure
+        idf.py build -v
+
+    - name: Upload build logs
+      uses: actions/upload-artifact@v3
+      if: failure()
+      with:
+        name: build-logs
+        path: |
+          build/log/idf_py_stdout_output_*
+          build/log/idf_py_stderr_output_*
 
     - name: Upload to FTP
       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
